alias gfr="git fetch && git rebase origin/develop --autostash"
alias gr="git rebase"
alias gl="git log --oneline -n"
alias gb="git branch"
alias gcn="git checkout -b "
alias gce="git checkout "
alias grh="git reset --hard"
alias gcp="git cherry-pick "
